name: Build-and-test
on:
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        git clone -b master --single-branch https://github.com/Guillelerial/loggingbot.git
        pip install -e loggingbot/
        pip install .
        
        pip install pylint
    - name: Lint with pylint
      run: |
        pylint pvpcservice --exit-zero --reports y

    - name: Test with pytest
      run: |
        pytest tests --cov=pvpcservice --cov-report term-missing --cov-report hmtl
